name: TryHackMe Update Badge

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *' 
  workflow_dispatch: # Allows you to run it manually anytime

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update TryHackMe Badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          # Your TryHackMe Username
          username: "mkzhm" 
          # Where to save the image in your repo
          image_path: "./assets/thm_propic.png"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
